### ISSUE TITLE
First available laser turret not able to reach spitters

### ISSUE THREAD

**Issue by Rikrik** [Dysoch/DyTech#233]
My base keeps getting overrun by spitters because my lasers can't reach them. They're just dancing around spitting my lasers to death and then continue to wreck my base while i'm out looking for ores.

Don't have the required tools to mine crystals yet so can't make any of the better lasers with better range. (Unless i'm missing a very obvious way to mine them)

**Comment by izofra** [comment]
hmm how much lasers you have ? my lasers protect my base perfectly. i got 200-300 lasers per base.

**Comment by Rikrik** [comment]
Even if i put down 50 the spitters will just stay out of their range and kill them, and when all 50 of the turrets have been brutally murdered they will move on to the rest of my base. It's the laser turret that just needs steel, electronic circuits and weak capacitors.

**Comment by Storybro** [comment]
I can confirm this. It could be possibly intentional, but if you load a map with already placed laser turrets (or make them via the default crafting recipe) the ruby turrets have a shorter range than spitting enemies, making them entirely useless as the spitters mow them down from a range. I expect you'd have to urgently work towards upgraded turrets to even begin to have a chance of survival with the war module active.

**Comment by hohounk** [comment]
I actually found it quite nice as finally gunturrents became useful due to having more than enough range :)
