### ISSUE TITLE
Unable to insert plate molds into forge

### ISSUE THREAD

**Issue by Dylock** [Dysoch/DyTech#278]
Plate molds can be removed from the forge by an inserter.  However, the plate molds cannot be reinserted into the forge.  I tried reinserting the molds from the sides with an inserter, and from the bottom.  Unsuccessful.  I have to insert them by hand.

Running all four DyTech mods (current as of first week March, 2015)

**Comment by SuicidalKid** [comment]
![inserter-loop- gif](https://cloud.githubusercontent.com/assets/10734162/6515430/c2bb026a-c357-11e4-8430-d849f8c9bda2.gif)

Works for me.

**Comment by Dylock** [comment]
Here's a link to my saved game:
https://www.dropbox.com/s/pdf8hivt65wd5al/What.zip?dl=0
Now I'm wondering why copper plate is coming out of an iron forge...

Factorio 0.11.16
DyCore 1.1.2
DyMachine 1.0.1
DyPower 1.0.0
DyWar 1.0.0
TreeFarm 1.2.7

**Comment by SuicidalKid** [comment]
You need to pull the iron out of the forge too, otherwise the inserter thinks it's backed up and won't put anymore molds into it. The copper is NOT coming from the forge, it's coming from the furnace below it. Move the inserter and it'll be good. For now, I'll upload a modified version of your save.

https://www.dropbox.com/s/6mdbfo26n26exzw/What.zip?dl=0
