### ISSUE TITLE
DyTech-Power 1.1.0 Error on map generation

### ISSUE THREAD

**Issue by SKleen75** [Dysoch/DyTech#337]
While starting my first game with DyTech on Factorio 12 i get this error.

![image](https://cloud.githubusercontent.com/assets/10866480/8849223/48b07806-313e-11e5-978b-06c4bd2f95a2.png)

Bug or my mistake?

**Comment by Bonsai555** [comment]
Hey SKleen75 you can fix this problem by renaming a folder: MAIN-DyTech-Power_1.1.0/"GUI" -> MAIN-DyTech-Power_1.1.0/"gui".  the problem is the case sensitivity. If Your are using Windows you can also come around and just unzip the modular parts of Dytech in the mods folder.
This Bug has been reported and fixed before. -> #318

**Comment by SKleen75** [comment]
Thanks.

**Comment by MagicLegend** [comment]
SORRYYYYYYYY
