### ISSUE TITLE
[Request] 1 Recipe for "Clean Ore" and not for each Ore seperate

### ISSUE THREAD

**Issue by windwind12** [Dysoch/DyTech#385]
1 Recipe for "Clean Ore" and not for each Ore seperate
The smelter also take all ores
Is this possible?

**Comment by Skillabstinenz** [comment]
same goes for corpse processing, yes i know, it was already simplified. I'm nearly evofactor 1 and they die in the hundreds. having to fine tune the processing for who died isn't fun.

**Comment by windwind12** [comment]
Corpse processing is OK ... there is no need for simplifing.
But with ore is it different. When i can burn it in 1 why i need for cleaning 1 for each.
I know that is much work, but it would be nice if you can do it.
If i known how i would do it by my own.

**Comment by Dysoch** [comment]
That means i have to make the centrifuge an furnace (automated recipe selector, not like the assembling machines) But that also means that each recipe can only require 1 input, and since cleaning ores requires the ore and water, that isnt possible.

I will think about a way to simply it, but it seems doubtful that it will happen

**Comment by windwind12** [comment]
OK, now i understand ...
Then close it and write it of you when me is boring list :-)
Its only a nice to have.
