### ISSUE TITLE
Cannot put productivity modules into Assembly Machine 6

### ISSUE THREAD

**Issue by Toudi2** [Dysoch/DyTech#390]
example recipe: copper cable
you can put all productivity modules into assembly machines 1-5
but possibly also affects assembly machine 7+ (havent tested yet)

**Comment by SensingIT-Youri** [comment]
I can confirm this happens for both tiers 6 and 7. You get the message ''Productivity module 8 can't be used in Assembling Machine 7".

When replacing a tier 5 or lower filled with Productivity module 8, these modules do stay inside the tier 6 or 7 that you're replacing with.

**Comment by Dysoch** [comment]
Intended Feature. The assembling machine 6 and 7 are fast. So if you want productivity boost, you must use 1-5

**Comment by gixbit** [comment]
Maybe you should force the modules to the player's inventory when the player upgrades a factory on the spot. Also, I'm not sure I agree with this feature. They feel like a downgrade, How about reducing the slots instead and still allowing those modules, But, Make them faster still. That way, no matter what anyone does, they can't get the same productivity out of these as factory 5s, and 6s and 7s can be used for things that need more speed instead of productivity. I'd say set the base speed high enough to achieve the effect of the 6 module slots now, but, reduce them to say 3 and 2 slots. 

![20](https://cloud.githubusercontent.com/assets/3877176/9610431/12daa5d6-50b4-11e5-9194-66f0dba9b37e.png)
