### ISSUE TITLE
Bronze Topaz Laser Turret recipe requires wrong turret

### ISSUE THREAD

**Issue by Quizer85** [Dysoch/DyTech#410]
[DyTech War 1.1.1]

The Bronze Topaz Laser Turret (laser-turret-sniper-1 in the recipe.lua) requires the Silver Sapphire Laser Turret to craft, but I think it is meant to require the Gold Sapphire turret.

**Comment by Skillabstinenz** [comment]
oh is it? i like the way it is.

**Comment by Quizer85** [comment]
It seems odd. I'd expect the next tier up to require the most upgraded turret from the previous tier. But if it works the way you meant it to, then it's fine.

**Comment by Skillabstinenz** [comment]
Do you really want to have that much upgrade "fun"?

You can build all the blue and green turrets from the standard one.
I have everything researched, 90 rockets send, the last 3 digits of my evo-factor aren't 9s, but my turrets are still only gold topaz. They were quite the hassle.
Not to image I had to build build r1->r2->r3->s1->s2->s3->e1->e2->e3->t1->t2->t3->d1->d2->d3 instead of the r1->s2->t1->t2->t3

This way you can can build the turrets you have the resources for.
ruby2-3: zinc
sapphire: gold zinc silver
emerald: tungsten lead cobalt ardite
topaz: circuits steel/tungsten
If you just have to upgrade them, you need all the resources and can't compensate missing/low resources on your map.

**Comment by Quizer85** [comment]
Speaking for myself, I do think upgrading stuff is fun. I hate upgrading to a better tier of equipment and having to throw the old gear away, and I like that for the most part it is unnecessary to do so in DyTech.

I do agree that the upgrade chain you described would be ridiculous, especially as the different gem colors vary a bit in their focus. It seems like r1->r2->r3->s1->s2->s3->t1->t2->t3 and r1->r2->r3->e1->e2->e3->d1->d2->d3 would be more reasonable. You could upgrade to the top ruby tier and use them as base to get to any other turret eventually. In that case, it might make sense to fiddle with the turret stats a little, though, maybe consider rebalancing the material costs, too.

Gold Topaz are my current goal as well, considering I've not discovered any cobalt or ardite deposits on my map yet. The diamond turrets output ridiculous damage, but the range of the topaz turrets is very appealing.

**Comment by Dysoch** [comment]
Gonna be changed in the rebalance of intermediates. Closing issue, since its done/nearly done.

Currently working on it :D
