### ISSUE TITLE
Dytech-Power 1.1.1 Multiplayer GUI issue

### ISSUE THREAD

**Issue by daniel34** [Dysoch/DyTech#420]
Dytech-Power 1.1.1 is not completely safe for multiplayer.
I guess it should be because the forum download topic only says that Dytech-Dynamics isn't multiplayer compatible / not tested.

The error occurs when you open the Dytech GUI on the top left, go into Dytech-Power and then use the Back button. The game ends and the dedicated server shuts down.
Message is displayed on screen for the client and in the server log:
Error Util.cpp:46: Error while running the event handler: __MAIN-DyTech-Power__/control.lua:179: Map doesn't contain 1 player, this function can't be used
The line in question is: game.player.gui.top["DyTechPowerFlow"].destroy()

Machine and War don't have a GUI, and the Core back button works, although it has the name Unknown key:"back" (localization issue?)

Server is a dedicated Debian machine with 8GB RAM, client a Windows 7 x64 machine Phenom II with 16 GB RAM, both running Factorio 0.12.7.

**Comment by followsound** [comment]
Can confirm I've had exactly this issue in multiplayer.

Windows Server 2012 as server
OSX Mavericks and Windows 7 clients

**Comment by MagicLegend** [comment]
I have tested the feature on an muliplayer map. Not an dedicated server, just an map which I have with an friend so there are in fact two players on the map according to the game. I'm not sure where it went wrong, probarly left some old code running... I'll fix this Friday (I hope, school is busy >.<)

**Comment by MagicLegend** [comment]
Hmm... Looking at the code, there shouldnt be an issue (the 'player' mentioned on the line is in fact an variable for the playerIndex (https://github.com/Dysoch/DyTech/blob/master/MAIN-DyTech-Power/control.lua#L249), so your line in question isnt correct/outdated. Could you post your build number (found in mods/DyTech-Power_x.x.x/build.txt) here? I want to know how old the build you have is. Thanks!

Ps. Gotta be honest, I have built this code against 0.12.2, and haven't updated my dev-environment since... Probarly need to test some code again ;-)

**Comment by followsound** [comment]
My build is:

DyTech-Power_1.1.1

Build 070815a

**Comment by MagicLegend** [comment]
ok, thanks. This is indeed the release build. I've just downloaded it myself, and I see that the bug isn't fixed there. Silly me. I'm sorry! I can't find in the commits I've made that this issue is fixed. Strange. I'll look into the most recent build, see if I can stamp it 'stable-ish' and make an new bugfix release.

This can take some time. For in the mean time, you can edit the line yourself (I think) by removing the 'game.' (so the word game and the dot after it). This should (in theory :p) fix the issue.

~ML

**Comment by followsound** [comment]
Thanks for the fix! Don't be sorry, the mod is great!

**Comment by followsound** [comment]
Thanks for the fix! Don't be sorry, the mod is great!

**Comment by MagicLegend** [comment]
I'll make an new beta release for power. I think the version can be considered stable, but I'm not 100% certain. The build is built against the DyTech-Core-1.2.1 release.

~ML

**Comment by MagicLegend** [comment]
https://github.com/Dysoch/DyTech/releases
