### ISSUE TITLE
0.12.11+ Compat

### ISSUE THREAD

**Issue by zlyfire** [Dysoch/DyTech#435]
Will dytech be updated to be compatible with 0.12.11+ factorio? It's been well over a month since the last commit to the repo. Is there any word in relation to this?

**Comment by MagicLegend** [comment]
Well, both dysoch and I are extremely busy. Dysoch was in the middle of updating the way the mod handles recipes, and I'm trying to continue this. But, I am also an exam student, and in a few months I'll have my final exams... Creating and mentaining something this big is extremely difficult, since it takes many hours to create an (simple) function. For instance; the steam engine GUI in Dytech-Power took me about 20-30 hours to make. That's a lot of time.

~ML

**Comment by zlyfire** [comment]
Okay, that's all understandable. Thank you for a response.

**Comment by Dysoch** [comment]
working on it, should be fixed soon :D
